name: Doit s'executer dans un custom runner
on: 
  #schedule: 
  #  - cron: "0 08 * * *"
  workflow_dispatch:
  push: 
    branches: 
      - master
      - main
env:
  ZIP_PATH: ${{ github.workspace }}

jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v4
        with: 
          distribution: "microsoft"
          java-version: "21"
      - name: create zip bundle
        run: |
          pwd
          echo $ZIP_PATH
          echo $LANGAGE
          echo ${{ secrets.PRIVATE_KEY}}
          cd $ZIP_PATH
          zip -r ../${{github.sha}}.zip .
      - name: archieve artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: env.ZIP_PATH
          overwrite: true
          
      
  
  
