name: Doit s'executer dans un custom runner
on: push

jobs:
  init:
    runs-on: self-hosted
    steps:
      - run: echo "Salut ${{ github }}."
      - run: echo "Ce workflow s'execute dans le repository ${{ github.repository }}."
      - run: echo "Ce worhflow s'execute sur $Hostname."
      
  
  
