name: Doit s'executer dans un custom runner
on: 
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  init:
    runs-on: self-hosted
    steps:
      - run: echo "Ce job est demarre sur le systeme d<exploitation ${{ runner.os }}."
      - run: echo "Ce workflow s'execute dans le repository ${{ github.repository }}."
      - run: echo "La branche utilisee est ${{ github.ref}}."
      - name: checkout le repository
        uses: actions/checkout@v4
      
  
  
