name: Doit s'executer dans un custom runner
on: 
  #schedule: 
  #  - cron: "0 08 * * *"
  workflow_dispatch:
  push: 
    branches: 
      - master
      - main
env:
  ZIP_PATH: ${{ github.workspace }}

jobs:
  init:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
        
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v4
        with: 
          distribution: "microsoft"
          java-version: "21"
      - name: create zip bundle with os
        run: |
          pwd
          echo ${{ env.ZIP_PATH }}
          echo ${{ secrets.PRIVATE_KEY}}
          cd ${{ env.ZIP_PATH }}
          if ($env:RUNNER_OS -eq "Windows") {
            Compress-Archive -Path ${{ env.ZIP_PATH }} -DestinationPath ${{ env.ZIP_PATH }}/${{github.sha}}.zip
          }
          else {zip -r ../${{github.sha}}.zip }
          
      - name: archieve artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ env.ZIP_PATH }}
          overwrite: true
          
      
  
  
